CREATE TABLE PEOPLE(
	PERSON_ID INTEGER PRIMARY KEY AUTO_INCREMENT, 
	FIRST_NAME VARCHAR(100), 
	MIDDLE_NAME VARCHAR(100), 
	LAST_NAME VARCHAR(100), 
	GENDER VARCHAR(20), 
	SSN VARCHAR(15), 
	BIRTHDATE VARCHAR(15), 
	OCCUPATION VARCHAR(100), 
	VEHICLE_MAKE VARCHAR(20), 
	VEHICLE_MODEL VARCHAR(20), 
	ADDRESS_LINE_1 VARCHAR(100), 
	ADDRESS_LINE_2 VARCHAR(100), 
	CITY VARCHAR(40), 
	STATE VARCHAR(4), 
	ZIP VARCHAR(10)
);